name: farmily
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

# ...
environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  video_player: ^2.5.1
  # (여기에 추가 패키지를 적어주세요)
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/loading.png
    - assets/logo.png
    - assets/videos/2.mp4
    - assets/person.png
